# Generated by Django 2.2.6 on 2019-10-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='TypeYatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TypeYatch',
                'verbose_name_plural': 'TypeYatchs',
            },
        ),
        migrations.CreateModel(
            name='Yatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now_add=True)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_yatch', to='voyage.TypeYatch')),
            ],
            options={
                'verbose_name': 'Yatch',
                'verbose_name_plural': 'Yatchs',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('note', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now_add=True)),
                ('typeYatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yatch_reservation', to='voyage.TypeYatch')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('date_depart', models.DateTimeField()),
                ('date_arrive', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now_add=True)),
                ('pays_arrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_destination_arrive', to='voyage.Pays')),
                ('pays_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays_destination_depart', to='voyage.Pays')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
    ]
