# Generated by Django 2.2.6 on 2019-10-03 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=250)),
                ('nom', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clent',
            old_name='titre',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='clent',
            name='description',
        ),
        migrations.AddField(
            model_name='clent',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog/comment'),
        ),
        migrations.AddField(
            model_name='clent',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='clent',
            name='icon',
        ),
        migrations.AddField(
            model_name='clent',
            name='icon',
            field=models.ManyToManyField(to='clientele.Social', verbose_name='social_clent'),
        ),
    ]
